sm:
  secret:
    name: "prod/monew"

spring:
  config:
    activate:
      on-profile: prod

  cloud:
    aws:
      credentials:
        instance-profile: true
  app:
    aws:
      s3:
        bucket-name: monew-prod-bucket

  boot:
    admin:
      client:
        enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_PROD_HOST}:${DB_PROD_PORT}/${DB_PROD_NAME}
    username: ${DB_PROD_USER}
    password: ${DB_PROD_PASSWORD}

  data:
    mongodb:
      uri: mongodb://mongo:asdf1234!@monew-cluster-182498323365.ap-northeast-2.docdb-elastic.amazonaws.com:27017/monew?tls=true&authMechanism=SCRAM-SHA-1&retryWrites=false

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        jdbc.time_zone: UTC
      open-in-view: false

logging:
  level:
    root: info
    org.hibernate: warn
    com.zaxxer.hikari: warn
    org.mongodb.driver: warn
    org.springframework.web: warn
    org.springframework.filter.CommonsRequestLoggingFilter: warn
    com.monew.monew_server: info